apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcloud-microservice
  labels:
    app: wordcloud-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordcloud-microservice
  template:
    metadata:
      labels:
        app: wordcloud-microservice
    spec:
      containers:
      - name: wordcloud-microservice
        image: ghcr.io/mind-informatica-srl/wordcloud-microservice:v0.0.2
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: production